### ISSUE TITLE
Hard to understand which well known principles of programming you use.

### ISSUE THREAD

**Issue by mezoni** [google/files.dart#13]
``` dart
abstract class HtmlFileSystemEntry implements FileSystemEntry {
  HtmlFileSystemEntry._(this._fs, this._path);
}
```

This class is an abstract class.
This class is a public class.
This class with a private constructor.

Public abstract class with a private constructor.

How can be called such programming techniques?

This technique only useful for the static classes.

Eg.

``` dart
abstract class Platform {
  Platform._internal();

  static final int foo = 0;
}
```

This class is an abstract class (cannot be instantiated).
This class is a public class  (cannot be used anywhere).
This class with a private constructor  (cannot be instantiated).

What wrong with this approach?

``` dart
abstract class HtmlFileSystemEntry implements FileSystemEntry {
}

class _HtmlFileSystemEntry implements HtmlFileSystemEntry {
  _HtmlFileSystemEntry(this._fs, this._path);
}
```

Of cource, if you really need `HtmlFileSystemEntry` interface.

P.S.

I know that you (possible) like a `Dartish` way.
But `Dartish` way (beloved by `ahe`) are not a right way for the many serious programmers.

This is because, if your `HtmlFileSystemEntry` is an interface purpose type then it has a wrong design.

``` dart
abstract class HtmlFileSystemEntry implements FileSystemEntry {
  final HtmlFileSystem _fs;
  final String _path;

  HtmlFileSystemEntry._(this._fs, this._path);

  String get path => _path;
}
```

Remeber: I cannot use it as an interface.

``` dart
// Missing concrete implementation 
// of getter 'HtmlFileSystemEntry._path',
// getter 'HtmlFileSystemEntry._fs'
// getter 'HtmlFileSystemEntry.path'
class MyHtmlFileSystemEntry implements HtmlFileSystemEntry {
}
```

If I cannot use it as an interface then why it is a
- Public
- Abstract
- Has a private constructor

Where is a logic?

**Comment by devoncarew** [comment]
Closing - we're deprecating this package.
